// src/components/Navigation.tsx
import * as React from "react";
import {
    NavLink
} from "react-router-dom";


export const Navigation = () => (
        <nav className="navbar is-transparent  is-fixed-top">
            <div id="navbarMenu" className="navbar-menu is-active">
                <div className="navbar-end">
                    <div className="tabs is-right">
                        <ul>
                            <li><NavLink activeClassName='is-active' to="/">Generator</NavLink> </li>
                            <li> <NavLink activeClassName='is-active' to="/about">About</NavLink> </li>
                        </ul>
                        <span className="navbar-item">
                            <a className="button is-dark is-outlined"
                                href="https://github.com/wwerner/bashplate">
                                <span>Source</span>
                                <span className="icon">
                                    <i className="fab fa-github"></i>
                                </span>
                            </a>
                        </span>
                    </div>
                </div>
            </div>
        </nav >
)

// src/components/Navigation.vue
<template>
  <nav class="navbar is-transparent  is-fixed-top">
    <div id="navbarMenu" class="navbar-menu is-active">
      <div class="navbar-end">
        <div class="tabs is-right">
          <ul>
            <li :class="{ 'is-active' : $route.path === '/' }">
              <router-link to="/">Generator</router-link>
            </li>
            <li :class="{ 'is-active' : $route.path === '/about' }">
              <router-link to="about">About</router-link>
            </li>
          </ul>
          <span class="navbar-item">
                <a class="button is-dark is-outlined"
                   href="https://github.com/wwerner/bashplate">
                    <span>Source</span>
                    <span class="icon">
                        <i class="fab fa-github"></i>
                    </span>
                </a>
            </span>
        </div>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'Navigation',
};
</script>
